CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
WITH cte AS(
SELECT salary, 
DENSE_RANK() OVER(ORDER BY salary DESC) AS "dr"
FROM Employee
) 
SELECT DISTINCT MAX(salary)
FROM cte 
WHERE dr=N
  );
END